import type { Pilar, TipoRespondente } from "./scoring";

export type PerguntaSeed = {
  ordem: number;
  texto: string;
  pilar: Pilar;
  publico: TipoRespondente;
};

export const PERGUNTAS: PerguntaSeed[] = [
  // ===== CULTURA ORGANIZACIONAL — COLABORADORES =====
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 1, texto: "Tenho medo de me expressar livremente com minha liderança." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 2, texto: "Sinto que meus erros são usados contra mim, e não como oportunidade de aprendizado." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 3, texto: "Percebo que há um clima de desconfiança entre as pessoas aqui." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 4, texto: "Sinto que determinados grupos ou pessoas são tratados de forma diferente e injusta." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 5, texto: "Não me sinto parte desta empresa, apenas executo tarefas." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 6, texto: "Vejo comportamentos desrespeitosos acontecerem com frequência sem qualquer consequência." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 7, texto: "Tenho receio de discordar da minha liderança mesmo quando acredito estar certo." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 8, texto: "A empresa fala em valores, mas as atitudes do dia a dia contradizem esses valores." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 9, texto: "Me sinto excluído das decisões que afetam diretamente o meu trabalho." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 10, texto: "Aqui é comum as pessoas ficarem caladas por medo de retaliação." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 11, texto: "Não me sinto acolhido quando passo por dificuldades pessoais que afetam o trabalho." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 12, texto: "A diversidade de opiniões não é valorizada nesta empresa." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 13, texto: "Percebo que há favoritismo na forma como as pessoas são tratadas." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 14, texto: "O ambiente aqui me faz sentir ansioso ou tenso com frequência." },
  { pilar: "CULTURA", publico: "COLABORADOR", ordem: 15, texto: "Sinto que minha presença aqui não faz diferença para ninguém." },

  // ===== CULTURA ORGANIZACIONAL — LÍDERES =====
  { pilar: "CULTURA", publico: "LIDER", ordem: 1, texto: "Tenho dificuldade em ouvir críticas ou divergências da minha equipe sem me sentir ameaçado." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 2, texto: "Quando alguém da minha equipe erra, minha primeira reação é cobrar responsabilidade, não entender o que aconteceu." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 3, texto: "Sinto que a cultura da empresa me obriga a ser rígido com meu time, mesmo quando discordo." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 4, texto: "Percebo que as pessoas da minha equipe evitam me dar más notícias." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 5, texto: "Tenho dificuldade em separar o profissional do pessoal quando há conflitos na equipe." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 6, texto: "Sinto que preciso esconder minhas próprias dificuldades para manter a autoridade." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 7, texto: "Não me sinto preparado para lidar com situações de diversidade e inclusão." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 8, texto: "O ambiente aqui me impede de ser um líder mais humano do que a empresa permite." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 9, texto: "Percebo que minha equipe não confia em mim, mas não sei como mudar isso." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 10, texto: "Sinto que a empresa não pratica os valores que prega, e isso afeta minha credibilidade com o time." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 11, texto: "Tenho dificuldade em reconhecer publicamente os erros que cometo diante da equipe." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 12, texto: "Quando há conflitos entre pessoas da equipe, prefiro ignorar do que intervir." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 13, texto: "Não consigo ser exemplo dos comportamentos que a empresa espera de todos." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 14, texto: "Sinto que a pressão de cima me força a repassar cobranças de forma que não concordo." },
  { pilar: "CULTURA", publico: "LIDER", ordem: 15, texto: "Percebo que há pessoas na minha equipe sendo excluídas ou marginalizadas e não sei como agir." },

  // ===== ORGANIZAÇÃO DO TRABALHO — COLABORADORES =====
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 1, texto: "Nunca está claro para mim o que fazer no meu dia a dia, minha gestão sempre dá ordens confusas." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 2, texto: "Regularmente executo tarefas que não são da minha função sem qualquer reconhecimento ou ajuste." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 3, texto: "Sinto que a quantidade de trabalho que recebo é incompatível com o tempo disponível." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 4, texto: "Não tenho os recursos necessários para executar minhas tarefas com qualidade." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 5, texto: "Meu trabalho frequentemente invade meu tempo pessoal e de descanso." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 6, texto: "As prioridades mudam de forma tão repentina que me sinto perdido no que devo fazer primeiro." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 7, texto: "Sinto que meu espaço ou estrutura de trabalho prejudica minha produtividade." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 8, texto: "Frequentemente preciso interromper o que estou fazendo para resolver urgências desnecessárias." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 9, texto: "Não tenho autonomia para organizar meu próprio trabalho do jeito que seria mais eficiente." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 10, texto: "Quando peço ajuda ou recursos, raramente recebo suporte adequado." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 11, texto: "O número de pessoas na equipe é insuficiente para a quantidade de demandas que temos." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 12, texto: "Sinto que trabalho mais do que deveria para compensar falhas na estrutura da empresa." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 13, texto: "Não consigo descansar de verdade fora do horário de trabalho porque me sinto obrigado a estar disponível." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 14, texto: "Minha função na empresa nunca foi explicada de forma clara e formal." },
  { pilar: "ORGANIZACAO", publico: "COLABORADOR", ordem: 15, texto: "Sinto que a empresa não se preocupa com meu equilíbrio entre vida e trabalho." },

  // ===== ORGANIZAÇÃO DO TRABALHO — LÍDERES =====
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 1, texto: "O volume de decisões que preciso tomar diariamente me sobrecarrega de forma insustentável." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 2, texto: "Tenho responsabilidades que vão muito além do que meu cargo formal deveria exigir." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 3, texto: "Não tenho recursos suficientes para entregar o que a empresa espera de mim e da minha equipe." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 4, texto: "Gerencio tantas equipes ou pessoas simultaneamente que não consigo dar atenção adequada a nenhuma." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 5, texto: "Frequentemente preciso resolver problemas que deveriam ser tratados por outras áreas ou níveis." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 6, texto: "Meu trabalho frequentemente invade meu tempo pessoal de forma que considero prejudicial." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 7, texto: "As demandas mudam tão rápido que fica impossível planejar e organizar o trabalho da equipe." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 8, texto: "Sinto que a estrutura da empresa cria mais obstáculos do que facilita meu trabalho como líder." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 9, texto: "Preciso tomar decisões importantes sem ter as informações necessárias para fazê-lo bem." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 10, texto: "Não tenho tempo hábil para desenvolver as pessoas da minha equipe por excesso de demandas operacionais." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 11, texto: "A empresa me cobra resultados, mas não me dá as condições para atingi-los." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 12, texto: "Frequentemente me sinto sozinho nas decisões difíceis, sem suporte de pares ou superiores." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 13, texto: "Sinto que minha equipe é pequena demais para a quantidade de trabalho que nos é atribuída." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 14, texto: "Não consigo descansar de verdade fora do horário porque a responsabilidade não para." },
  { pilar: "ORGANIZACAO", publico: "LIDER", ordem: 15, texto: "Sinto que a empresa não considera o impacto da carga de trabalho na saúde das lideranças." },

  // ===== METAS E PERFORMANCE — COLABORADORES =====
  { pilar: "METAS", publico: "COLABORADOR", ordem: 1, texto: "As metas que recebo raramente são atingíveis considerando os recursos que tenho disponíveis." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 2, texto: "Não entendo com clareza como serei avaliado no meu trabalho." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 3, texto: "Sinto que as cobranças que recebo são desproporcionais ao suporte que me é oferecido." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 4, texto: "Os critérios de avaliação mudam com frequência sem que eu seja informado previamente." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 5, texto: "Percebo que pessoas com desempenhos similares são avaliadas de formas diferentes." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 6, texto: "Sinto que serei punido se não atingir metas que considero impossíveis." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 7, texto: "Não tenho autonomia suficiente para atingir os resultados que me são cobrados." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 8, texto: "As metas individuais que recebo não fazem sentido para mim, parece que não se encaixam no todo." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 9, texto: "Frequentemente descubro que estou sendo cobrado por algo que não foi combinado antes." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 10, texto: "As avaliações de desempenho aqui parecem subjetivas e dependem mais de quem você conhece do que do que faz." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 11, texto: "Sinto que a empresa usa métricas para pressionar, não para desenvolver." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 12, texto: "Não recebo feedback claro sobre meu desempenho entre um ciclo de avaliação e outro." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 13, texto: "As metas estipuladas desconsideram completamente as condições reais do mercado ou do meu trabalho." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 14, texto: "Tenho medo de não atingir metas e sofrer consequências desproporcionais." },
  { pilar: "METAS", publico: "COLABORADOR", ordem: 15, texto: "Percebo que o sistema de reconhecimento e bônus não reflete de forma justa o esforço de cada um." },

  // ===== METAS E PERFORMANCE — LÍDERES =====
  { pilar: "METAS", publico: "LIDER", ordem: 1, texto: "As metas que me são impostas são incompatíveis com os recursos que tenho para atingi-las." },
  { pilar: "METAS", publico: "LIDER", ordem: 2, texto: "Sinto que sou responsabilizado por resultados que dependem de fatores fora do meu controle." },
  { pilar: "METAS", publico: "LIDER", ordem: 3, texto: "A pressão por metas afeta minha saúde e qualidade de vida de forma significativa." },
  { pilar: "METAS", publico: "LIDER", ordem: 4, texto: "Não tenho autonomia real para adaptar estratégias quando percebo que o caminho atual não funciona." },
  { pilar: "METAS", publico: "LIDER", ordem: 5, texto: "As cobranças que recebo da diretoria entram em conflito com o que sei ser factível para minha equipe." },
  { pilar: "METAS", publico: "LIDER", ordem: 6, texto: "Sinto que preciso repassar pressão para minha equipe de uma forma que não concordo." },
  { pilar: "METAS", publico: "LIDER", ordem: 7, texto: "Os indicadores que uso para medir minha equipe não refletem o que realmente importa." },
  { pilar: "METAS", publico: "LIDER", ordem: 8, texto: "Percebo que serei avaliado negativamente mesmo quando os fatores externos prejudicam meus resultados." },
  { pilar: "METAS", publico: "LIDER", ordem: 9, texto: "Não há coerência entre o que a empresa diz valorizar e o que de fato cobra de mim." },
  { pilar: "METAS", publico: "LIDER", ordem: 10, texto: "Sinto que meu desempenho é julgado de forma subjetiva e pouco transparente." },
  { pilar: "METAS", publico: "LIDER", ordem: 11, texto: "Frequentemente descubro que fui avaliado por critérios que não foram comunicados previamente." },
  { pilar: "METAS", publico: "LIDER", ordem: 12, texto: "A pressão por resultados de curto prazo me impede de tomar decisões melhores no longo prazo." },
  { pilar: "METAS", publico: "LIDER", ordem: 13, texto: "Não há reconhecimento quando as metas são atingidas, só cobrança quando não são." },
  { pilar: "METAS", publico: "LIDER", ordem: 14, texto: "Sinto que os rituais de avaliação de desempenho aqui são mais punitivos do que construtivos." },
  { pilar: "METAS", publico: "LIDER", ordem: 15, texto: "A empresa não me dá suporte adequado quando não estou conseguindo atingir os resultados esperados." },

  // ===== LIDERANÇA E GESTÃO DE PESSOAS — COLABORADORES =====
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 1, texto: "Não confio na minha liderança para tomar decisões que sejam boas para mim e para a equipe." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 2, texto: "O feedback que recebo da minha liderança é vago, tardio ou simplesmente inexistente." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 3, texto: "Quando enfrento dificuldades no trabalho, minha liderança não está disponível para me apoiar." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 4, texto: "Percebo que meu gestor trata pessoas diferentes de formas diferentes sem critério claro." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 5, texto: "Minha liderança não tem tempo ou disposição para me ouvir quando preciso." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 6, texto: "Recebo críticas constantes sem reconhecimento pelos acertos que tenho." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 7, texto: "Meu gestor frequentemente age de forma que considero desrespeitosa." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 8, texto: "Não me sinto desenvolvido pela liderança atual, sinto que estou estagnado." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 9, texto: "As decisões da minha liderança parecem arbitrárias e sem lógica clara." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 10, texto: "Percebo que minha liderança não tem preparo para lidar com situações de crise ou conflito." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 11, texto: "Sinto que sou microgerenciado e não tenho liberdade para executar meu trabalho com autonomia." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 12, texto: "Minha liderança não defende a equipe quando há pressão ou críticas externas." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 13, texto: "As informações importantes raramente chegam a mim de forma clara e antecipada pela liderança." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 14, texto: "Percebo que minha liderança favorece determinadas pessoas em detrimento de outras." },
  { pilar: "LIDERANCA", publico: "COLABORADOR", ordem: 15, texto: "Não sinto que meu desenvolvimento profissional é uma prioridade para minha liderança." },

  // ===== LIDERANÇA E GESTÃO DE PESSOAS — LÍDERES =====
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 1, texto: "Não tenho autonomia real para tomar decisões sobre minha própria equipe." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 2, texto: "Sinto que não fui adequadamente preparado para exercer a função de liderança que ocupo." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 3, texto: "Não consigo desenvolver as pessoas da minha equipe por falta de tempo, recursos ou suporte." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 4, texto: "Tenho dificuldade em dar feedback de forma estruturada e constante para minha equipe." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 5, texto: "Percebo que há conflitos recorrentes na minha equipe que não sei como resolver." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 6, texto: "Não recebo reconhecimento da empresa pelo trabalho que faço como líder." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 7, texto: "As informações que preciso para liderar bem raramente chegam de forma clara e antecipada." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 8, texto: "Sinto que a empresa não investe no meu desenvolvimento como líder." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 9, texto: "Fico preso entre o que minha equipe precisa e o que a empresa exige de mim." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 10, texto: "Não recebo feedbacks claros sobre minha performance como gestor." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 11, texto: "Sinto que minha autoridade é constantemente questionada ou minada pela estrutura da empresa." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 12, texto: "Tenho dificuldade em manter minha equipe motivada dadas as condições atuais da empresa." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 13, texto: "Percebo que a comunicação entre as lideranças e a diretoria é falha e me prejudica." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 14, texto: "Sinto que não tenho suporte emocional ou estrutural para lidar com os desafios da liderança." },
  { pilar: "LIDERANCA", publico: "LIDER", ordem: 15, texto: "A empresa não me dá as ferramentas que preciso para ser um líder de qualidade." },
];
